### ISSUE TITLE
[MC 1.21] No such Optional value in Death Record

### ISSUE THREAD

**Issue by cplir-c** [JackFred2/LenientDeath#14]
I got killed by a zombie and crashed:

```
[00:31:52] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1025) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:912) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
	at red.jackf.lenientdeath.restoreinventory.DeathRecord.lambda$toTag$11(DeathRecord.java:102) ~[lenientdeath-1.2.3+1.21.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at red.jackf.lenientdeath.restoreinventory.DeathRecord.toTag(DeathRecord.java:101) ~[lenientdeath-1.2.3+1.21.jar:?]
	at red.jackf.lenientdeath.restoreinventory.RestoreInventory.saveDeathHistory(RestoreInventory.java:67) ~[lenientdeath-1.2.3+1.21.jar:?]
	at red.jackf.lenientdeath.restoreinventory.RestoreInventory.onDeath(RestoreInventory.java:100) ~[lenientdeath-1.2.3+1.21.jar:?]
	at MC/net.minecraft.server.level.ServerPlayer.handler$elp000$lenientdeath$saveDeathRecordBeforeClearing(ServerPlayer.java:11119) ~[client-intermediary.jar:?]
	at MC/net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1252) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.player.Player.hurt(Player.java:977) ~[client-intermediary.jar:?]
	at MC/net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:811) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1502) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.monster.Zombie.doHurtTarget(Zombie.java:354) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:151) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:144) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.ai.goal.ZombieAttackGoal.tick(ZombieAttackGoal.java:28) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:65) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:112) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:103) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.Mob.serverAiStep(Mob.java:794) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2778) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.Mob.aiStep(Mob.java:572) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:266) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2507) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.Mob.tick(Mob.java:372) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.monster.Monster.tick(Monster.java:1568) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:238) ~[client-intermediary.jar:?]
	at MC/net.minecraft.server.level.ServerLevel.mixinextras$bridge$method_5773$256(ServerLevel.java) ~[client-intermediary.jar:?]
	at MC/net.minecraft.server.level.ServerLevel.wrapOperation$hie000$puzzleslib$tickNonPassenger(ServerLevel.java:18297) ~[client-intermediary.jar:?]
	at MC/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:770) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.level.Level.guardEntityTick(Level.java:498) ~[client-intermediary.jar:?]
	at MC/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:408) ~[client-intermediary.jar:?]
	at MC/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[client-intermediary.jar:?]
	at MC/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:372) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1021) ~[client-intermediary.jar:?]
	... 5 more
```

**Comment by JackFred2** [comment]
Fixed in 1.2.5 out in a bit
